In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\19641\OSS_Project\opensourceproject\bicycle\df_bicycle.csv")

In [3]:
df

,반납위도,반납경도,반납대여소번호,대여위도,대여경도,대여대여소번호,대여일시,반납일시
0,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-03 09:57:31,2019-01-03 10:11:35
1,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-04 14:00:53,2019-01-04 14:06:32
2,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-04 18:29:43,2019-01-04 19:15:47
3,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-06 14:12:34,2019-01-06 14:59:50
4,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-07 19:35:34,2019-01-07 20:08:06
5,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 11:17:09,2019-01-13 12:01:49
6,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 13:37:48,2019-01-13 13:58:40
7,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 14:23:41,2019-01-13 15:19:49
8,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 20:28:15,2019-01-15 21:11:51
9,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 21:42:09,2019-01-15 21:58:30
10,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 23:45:11,2019-01-16 00:47:05
11,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-16 19:52:47,2019-01-16 20:24:50
12,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 10:59:57,2019-01-19 12:19:41
13,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 12:20:13,2019-01-19 13:51:38
14,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 13:53:59,2019-01-19 15:49:53
15,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 15:50:24,2019-01-19 17:30:06
16,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 23:06:16,2019-01-20 00:10:58
17,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 09:25:12,2019-01-20 11:19:35
18,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 11:20:03,2019-01-20 12:02:41
19,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 17:24:09,2019-01-20 17:35:54
20,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-21 03:12:32,2019-01-21 05:05:10
21,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-23 15:52:26,2019-01-23 17:38:47
22,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-25 12:42:50,2019-01-25 13:13:48
23,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 15:31:32,2019-01-26 16:26:28
24,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 18:55:36,2019-01-26 19:52:07
25,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 19:50:00,2019-01-26 20:03:13
26,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 23:26:27,2019-01-26 23:48:54
27,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 17:16:00,2019-01-27 18:03:35
28,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 18:59:45,2019-01-27 19:13:38
29,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 23:50:28,2019-01-27 23:54:43
...,...,...,...,...,...,...,...,...
5380860,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 01:19:52,2019-05-24 02:13:23
5380861,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 15:00:12,2019-05-24 15:22:38
5380862,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 17:08:42,2019-05-24 17:42:54
5380863,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 21:31:11,2019-05-24 22:16:58
5380864,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 09:23:50,2019-05-25 10:04:18
5380865,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 12:28:26,2019-05-25 13:24:15
5380866,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 16:56:54,2019-05-25 17:54:10
5380867,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 18:54:03,2019-05-25 19:38:25
5380868,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 19:03:56,2019-05-25 20:44:25
5380869,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:22:09,2019-05-25 23:07:44
5380870,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:20:25,2019-05-25 23:07:56
5380871,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:18:29,2019-05-25 23:08:01
5380872,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 13:04:34,2019-05-26 13:24:08
5380873,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 17:11:43,2019-05-26 17:46:00
5380874,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 20:59:56,2019-05-26 21:51:09
5380875,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 22:21:42,2019-05-27 00:13:50
5380876,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 22:21:20,2019-05-27 05:40:35
5380877,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-27 05:41:25,2019-05-27 05:54:36
5380878,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-27 17:00:52,2019-05-27 17:10:44
5380879,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 05:45:19,2019-05-28 05:52:05
5380880,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 08:25:19,2019-05-28 10:10:27
5380881,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 15:24:35,2019-05-28 15:54:14
5380882,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 17:29:00,2019-05-28 18:18:28
5380883,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 20:25:55,2019-05-28 20:29:06
5380884,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-29 17:35:35,2019-05-29 17:51:36
5380885,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-29 22:07:08,2019-05-29 23:09:24
5380886,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 05:55:57,2019-05-30 06:03:06
5380887,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 08:19:39,2019-05-30 10:07:55
5380888,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 15:07:22,2019-05-30 15:31:08
5380889,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-31 08:35:27,2019-05-31 08:47:34

In [4]:
arr =  pd.read_csv(r"C:\Users\19641\OSS_Project\opensourceproject\bicycle\using_No.csv",names = ["station_No"])

In [5]:
arr

      station_No
0            101
1            102
2            103
3            104
4            105
5            106
6            107
7            108
8            109
9            110
10           111
11           112
12           113
13           114
14           115
15           116
16           118
17           119
18           120
19           121
20           122
21           123
22           124
23           125
24           126
25           127
26           128
27           129
28           130
29           131
...          ...
1470        3510
1471        3511
1472        3513
1473        3514
1474        3515
1475        3516
1476        3517
1477        3518
1478        3519
1479        3520
1480        3521
1481        3522
1482        3523
1483        3524
1484        3525
1485        3527
1486        3528
1487        3529
1488        3530
1489        3531
1490        3532
1491        3533
1492        3534
1493        3535
1494        3536
1495        3537
1496        3538
1497        3539
1498        3541
1499        3542

[1500 rows x 1 columns]

In [6]:
arr['station_No'] = arr['station_No'].astype(str)

In [7]:
df = df[df["반납대여소번호"].isin(arr['station_No'])]
df = df.reset_index(drop=True)
df

,반납위도,반납경도,반납대여소번호,대여위도,대여경도,대여대여소번호,대여일시,반납일시
0,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-03 09:57:31,2019-01-03 10:11:35
1,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-04 14:00:53,2019-01-04 14:06:32
2,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-04 18:29:43,2019-01-04 19:15:47
3,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-06 14:12:34,2019-01-06 14:59:50
4,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-07 19:35:34,2019-01-07 20:08:06
5,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 11:17:09,2019-01-13 12:01:49
6,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 13:37:48,2019-01-13 13:58:40
7,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 14:23:41,2019-01-13 15:19:49
8,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 20:28:15,2019-01-15 21:11:51
9,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 21:42:09,2019-01-15 21:58:30
10,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 23:45:11,2019-01-16 00:47:05
11,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-16 19:52:47,2019-01-16 20:24:50
12,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 10:59:57,2019-01-19 12:19:41
13,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 12:20:13,2019-01-19 13:51:38
14,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 13:53:59,2019-01-19 15:49:53
15,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 15:50:24,2019-01-19 17:30:06
16,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 23:06:16,2019-01-20 00:10:58
17,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 09:25:12,2019-01-20 11:19:35
18,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 11:20:03,2019-01-20 12:02:41
19,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 17:24:09,2019-01-20 17:35:54
20,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-21 03:12:32,2019-01-21 05:05:10
21,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-23 15:52:26,2019-01-23 17:38:47
22,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-25 12:42:50,2019-01-25 13:13:48
23,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 15:31:32,2019-01-26 16:26:28
24,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 18:55:36,2019-01-26 19:52:07
25,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 19:50:00,2019-01-26 20:03:13
26,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 23:26:27,2019-01-26 23:48:54
27,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 17:16:00,2019-01-27 18:03:35
28,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 18:59:45,2019-01-27 19:13:38
29,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 23:50:28,2019-01-27 23:54:43
...,...,...,...,...,...,...,...,...
5351341,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 01:19:52,2019-05-24 02:13:23
5351342,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 15:00:12,2019-05-24 15:22:38
5351343,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 17:08:42,2019-05-24 17:42:54
5351344,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 21:31:11,2019-05-24 22:16:58
5351345,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 09:23:50,2019-05-25 10:04:18
5351346,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 12:28:26,2019-05-25 13:24:15
5351347,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 16:56:54,2019-05-25 17:54:10
5351348,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 18:54:03,2019-05-25 19:38:25
5351349,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 19:03:56,2019-05-25 20:44:25
5351350,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:22:09,2019-05-25 23:07:44
5351351,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:20:25,2019-05-25 23:07:56
5351352,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:18:29,2019-05-25 23:08:01
5351353,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 13:04:34,2019-05-26 13:24:08
5351354,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 17:11:43,2019-05-26 17:46:00
5351355,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 20:59:56,2019-05-26 21:51:09
5351356,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 22:21:42,2019-05-27 00:13:50
5351357,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 22:21:20,2019-05-27 05:40:35
5351358,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-27 05:41:25,2019-05-27 05:54:36
5351359,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-27 17:00:52,2019-05-27 17:10:44
5351360,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 05:45:19,2019-05-28 05:52:05
5351361,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 08:25:19,2019-05-28 10:10:27
5351362,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 15:24:35,2019-05-28 15:54:14
5351363,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 17:29:00,2019-05-28 18:18:28
5351364,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 20:25:55,2019-05-28 20:29:06
5351365,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-29 17:35:35,2019-05-29 17:51:36
5351366,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-29 22:07:08,2019-05-29 23:09:24
5351367,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 05:55:57,2019-05-30 06:03:06
5351368,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 08:19:39,2019-05-30 10:07:55
5351369,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 15:07:22,2019-05-30 15:31:08
5351370,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-31 08:35:27,2019-05-31 08:47:34

In [8]:
df = df[df["대여대여소번호"].isin(arr['station_No'])]
df = df.reset_index(drop=True)
df

,반납위도,반납경도,반납대여소번호,대여위도,대여경도,대여대여소번호,대여일시,반납일시
0,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-03 09:57:31,2019-01-03 10:11:35
1,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-04 14:00:53,2019-01-04 14:06:32
2,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-04 18:29:43,2019-01-04 19:15:47
3,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-06 14:12:34,2019-01-06 14:59:50
4,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-07 19:35:34,2019-01-07 20:08:06
5,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 11:17:09,2019-01-13 12:01:49
6,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 13:37:48,2019-01-13 13:58:40
7,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-13 14:23:41,2019-01-13 15:19:49
8,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 20:28:15,2019-01-15 21:11:51
9,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 21:42:09,2019-01-15 21:58:30
10,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-15 23:45:11,2019-01-16 00:47:05
11,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-16 19:52:47,2019-01-16 20:24:50
12,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 10:59:57,2019-01-19 12:19:41
13,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 12:20:13,2019-01-19 13:51:38
14,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 13:53:59,2019-01-19 15:49:53
15,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 15:50:24,2019-01-19 17:30:06
16,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-19 23:06:16,2019-01-20 00:10:58
17,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 09:25:12,2019-01-20 11:19:35
18,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 11:20:03,2019-01-20 12:02:41
19,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-20 17:24:09,2019-01-20 17:35:54
20,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-21 03:12:32,2019-01-21 05:05:10
21,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-23 15:52:26,2019-01-23 17:38:47
22,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-25 12:42:50,2019-01-25 13:13:48
23,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 15:31:32,2019-01-26 16:26:28
24,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 18:55:36,2019-01-26 19:52:07
25,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 19:50:00,2019-01-26 20:03:13
26,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-26 23:26:27,2019-01-26 23:48:54
27,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 17:16:00,2019-01-27 18:03:35
28,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 18:59:45,2019-01-27 19:13:38
29,37.549561,126.905754,101,37.549561,126.905754,101,2019-01-27 23:50:28,2019-01-27 23:54:43
...,...,...,...,...,...,...,...,...
5325963,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 01:19:52,2019-05-24 02:13:23
5325964,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 15:00:12,2019-05-24 15:22:38
5325965,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 17:08:42,2019-05-24 17:42:54
5325966,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-24 21:31:11,2019-05-24 22:16:58
5325967,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 09:23:50,2019-05-25 10:04:18
5325968,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 12:28:26,2019-05-25 13:24:15
5325969,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 16:56:54,2019-05-25 17:54:10
5325970,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 18:54:03,2019-05-25 19:38:25
5325971,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 19:03:56,2019-05-25 20:44:25
5325972,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:22:09,2019-05-25 23:07:44
5325973,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:20:25,2019-05-25 23:07:56
5325974,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-25 22:18:29,2019-05-25 23:08:01
5325975,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 13:04:34,2019-05-26 13:24:08
5325976,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 17:11:43,2019-05-26 17:46:00
5325977,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 20:59:56,2019-05-26 21:51:09
5325978,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 22:21:42,2019-05-27 00:13:50
5325979,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-26 22:21:20,2019-05-27 05:40:35
5325980,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-27 05:41:25,2019-05-27 05:54:36
5325981,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-27 17:00:52,2019-05-27 17:10:44
5325982,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 05:45:19,2019-05-28 05:52:05
5325983,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 08:25:19,2019-05-28 10:10:27
5325984,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 15:24:35,2019-05-28 15:54:14
5325985,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 17:29:00,2019-05-28 18:18:28
5325986,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-28 20:25:55,2019-05-28 20:29:06
5325987,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-29 17:35:35,2019-05-29 17:51:36
5325988,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-29 22:07:08,2019-05-29 23:09:24
5325989,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 05:55:57,2019-05-30 06:03:06
5325990,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 08:19:39,2019-05-30 10:07:55
5325991,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-30 15:07:22,2019-05-30 15:31:08
5325992,37.545040,127.089958,3542,37.545040,127.089958,3542,2019-05-31 08:35:27,2019-05-31 08:47:34

In [9]:
origin = df[['반납대여소번호','대여대여소번호','반납일시','대여일시']].copy()
destination = df[['반납대여소번호','대여대여소번호','반납일시','대여일시']].copy()

In [10]:
origin['Path ID'] =  'No.' + origin['반납대여소번호'].map(str)+ '_' +  'No.' + origin['대여대여소번호'].map(str)
origin['Origin-Destination']='Origin'

In [11]:
origin

,반납대여소번호,대여대여소번호,반납일시,대여일시,Path ID,Origin-Destination
0,101,101,2019-01-03 10:11:35,2019-01-03 09:57:31,No.101_No.101,Origin
1,101,101,2019-01-04 14:06:32,2019-01-04 14:00:53,No.101_No.101,Origin
2,101,101,2019-01-04 19:15:47,2019-01-04 18:29:43,No.101_No.101,Origin
3,101,101,2019-01-06 14:59:50,2019-01-06 14:12:34,No.101_No.101,Origin
4,101,101,2019-01-07 20:08:06,2019-01-07 19:35:34,No.101_No.101,Origin
5,101,101,2019-01-13 12:01:49,2019-01-13 11:17:09,No.101_No.101,Origin
6,101,101,2019-01-13 13:58:40,2019-01-13 13:37:48,No.101_No.101,Origin
7,101,101,2019-01-13 15:19:49,2019-01-13 14:23:41,No.101_No.101,Origin
8,101,101,2019-01-15 21:11:51,2019-01-15 20:28:15,No.101_No.101,Origin
9,101,101,2019-01-15 21:58:30,2019-01-15 21:42:09,No.101_No.101,Origin
10,101,101,2019-01-16 00:47:05,2019-01-15 23:45:11,No.101_No.101,Origin
11,101,101,2019-01-16 20:24:50,2019-01-16 19:52:47,No.101_No.101,Origin
12,101,101,2019-01-19 12:19:41,2019-01-19 10:59:57,No.101_No.101,Origin
13,101,101,2019-01-19 13:51:38,2019-01-19 12:20:13,No.101_No.101,Origin
14,101,101,2019-01-19 15:49:53,2019-01-19 13:53:59,No.101_No.101,Origin
15,101,101,2019-01-19 17:30:06,2019-01-19 15:50:24,No.101_No.101,Origin
16,101,101,2019-01-20 00:10:58,2019-01-19 23:06:16,No.101_No.101,Origin
17,101,101,2019-01-20 11:19:35,2019-01-20 09:25:12,No.101_No.101,Origin
18,101,101,2019-01-20 12:02:41,2019-01-20 11:20:03,No.101_No.101,Origin
19,101,101,2019-01-20 17:35:54,2019-01-20 17:24:09,No.101_No.101,Origin
20,101,101,2019-01-21 05:05:10,2019-01-21 03:12:32,No.101_No.101,Origin
21,101,101,2019-01-23 17:38:47,2019-01-23 15:52:26,No.101_No.101,Origin
22,101,101,2019-01-25 13:13:48,2019-01-25 12:42:50,No.101_No.101,Origin
23,101,101,2019-01-26 16:26:28,2019-01-26 15:31:32,No.101_No.101,Origin
24,101,101,2019-01-26 19:52:07,2019-01-26 18:55:36,No.101_No.101,Origin
25,101,101,2019-01-26 20:03:13,2019-01-26 19:50:00,No.101_No.101,Origin
26,101,101,2019-01-26 23:48:54,2019-01-26 23:26:27,No.101_No.101,Origin
27,101,101,2019-01-27 18:03:35,2019-01-27 17:16:00,No.101_No.101,Origin
28,101,101,2019-01-27 19:13:38,2019-01-27 18:59:45,No.101_No.101,Origin
29,101,101,2019-01-27 23:54:43,2019-01-27 23:50:28,No.101_No.101,Origin
...,...,...,...,...,...,...
5325963,3542,3542,2019-05-24 02:13:23,2019-05-24 01:19:52,No.3542_No.3542,Origin
5325964,3542,3542,2019-05-24 15:22:38,2019-05-24 15:00:12,No.3542_No.3542,Origin
5325965,3542,3542,2019-05-24 17:42:54,2019-05-24 17:08:42,No.3542_No.3542,Origin
5325966,3542,3542,2019-05-24 22:16:58,2019-05-24 21:31:11,No.3542_No.3542,Origin
5325967,3542,3542,2019-05-25 10:04:18,2019-05-25 09:23:50,No.3542_No.3542,Origin
5325968,3542,3542,2019-05-25 13:24:15,2019-05-25 12:28:26,No.3542_No.3542,Origin
5325969,3542,3542,2019-05-25 17:54:10,2019-05-25 16:56:54,No.3542_No.3542,Origin
5325970,3542,3542,2019-05-25 19:38:25,2019-05-25 18:54:03,No.3542_No.3542,Origin
5325971,3542,3542,2019-05-25 20:44:25,2019-05-25 19:03:56,No.3542_No.3542,Origin
5325972,3542,3542,2019-05-25 23:07:44,2019-05-25 22:22:09,No.3542_No.3542,Origin
5325973,3542,3542,2019-05-25 23:07:56,2019-05-25 22:20:25,No.3542_No.3542,Origin
5325974,3542,3542,2019-05-25 23:08:01,2019-05-25 22:18:29,No.3542_No.3542,Origin
5325975,3542,3542,2019-05-26 13:24:08,2019-05-26 13:04:34,No.3542_No.3542,Origin
5325976,3542,3542,2019-05-26 17:46:00,2019-05-26 17:11:43,No.3542_No.3542,Origin
5325977,3542,3542,2019-05-26 21:51:09,2019-05-26 20:59:56,No.3542_No.3542,Origin
5325978,3542,3542,2019-05-27 00:13:50,2019-05-26 22:21:42,No.3542_No.3542,Origin
5325979,3542,3542,2019-05-27 05:40:35,2019-05-26 22:21:20,No.3542_No.3542,Origin
5325980,3542,3542,2019-05-27 05:54:36,2019-05-27 05:41:25,No.3542_No.3542,Origin
5325981,3542,3542,2019-05-27 17:10:44,2019-05-27 17:00:52,No.3542_No.3542,Origin
5325982,3542,3542,2019-05-28 05:52:05,2019-05-28 05:45:19,No.3542_No.3542,Origin
5325983,3542,3542,2019-05-28 10:10:27,2019-05-28 08:25:19,No.3542_No.3542,Origin
5325984,3542,3542,2019-05-28 15:54:14,2019-05-28 15:24:35,No.3542_No.3542,Origin
5325985,3542,3542,2019-05-28 18:18:28,2019-05-28 17:29:00,No.3542_No.3542,Origin
5325986,3542,3542,2019-05-28 20:29:06,2019-05-28 20:25:55,No.3542_No.3542,Origin
5325987,3542,3542,2019-05-29 17:51:36,2019-05-29 17:35:35,No.3542_No.3542,Origin
5325988,3542,3542,2019-05-29 23:09:24,2019-05-29 22:07:08,No.3542_No.3542,Origin
5325989,3542,3542,2019-05-30 06:03:06,2019-05-30 05:55:57,No.3542_No.3542,Origin
5325990,3542,3542,2019-05-30 10:07:55,2019-05-30 08:19:39,No.3542_No.3542,Origin
5325991,3542,3542,2019-05-30 15:31:08,2019-05-30 15:07:22,No.3542_No.3542,Origin
5325992,3542,3542,2019-05-31 08:47:34,2019-05-31 08:35:27,No.3542_No.3542,Origin

In [12]:
destination['Path ID'] = 'No.' + destination['반납대여소번호'].map(str) + '_' +  'No.' + destination['대여대여소번호'].map(str)
destination['Origin-Destination']='Destination'

In [13]:
destination

,반납대여소번호,대여대여소번호,반납일시,대여일시,Path ID,Origin-Destination
0,101,101,2019-01-03 10:11:35,2019-01-03 09:57:31,No.101_No.101,Destination
1,101,101,2019-01-04 14:06:32,2019-01-04 14:00:53,No.101_No.101,Destination
2,101,101,2019-01-04 19:15:47,2019-01-04 18:29:43,No.101_No.101,Destination
3,101,101,2019-01-06 14:59:50,2019-01-06 14:12:34,No.101_No.101,Destination
4,101,101,2019-01-07 20:08:06,2019-01-07 19:35:34,No.101_No.101,Destination
5,101,101,2019-01-13 12:01:49,2019-01-13 11:17:09,No.101_No.101,Destination
6,101,101,2019-01-13 13:58:40,2019-01-13 13:37:48,No.101_No.101,Destination
7,101,101,2019-01-13 15:19:49,2019-01-13 14:23:41,No.101_No.101,Destination
8,101,101,2019-01-15 21:11:51,2019-01-15 20:28:15,No.101_No.101,Destination
9,101,101,2019-01-15 21:58:30,2019-01-15 21:42:09,No.101_No.101,Destination
10,101,101,2019-01-16 00:47:05,2019-01-15 23:45:11,No.101_No.101,Destination
11,101,101,2019-01-16 20:24:50,2019-01-16 19:52:47,No.101_No.101,Destination
12,101,101,2019-01-19 12:19:41,2019-01-19 10:59:57,No.101_No.101,Destination
13,101,101,2019-01-19 13:51:38,2019-01-19 12:20:13,No.101_No.101,Destination
14,101,101,2019-01-19 15:49:53,2019-01-19 13:53:59,No.101_No.101,Destination
15,101,101,2019-01-19 17:30:06,2019-01-19 15:50:24,No.101_No.101,Destination
16,101,101,2019-01-20 00:10:58,2019-01-19 23:06:16,No.101_No.101,Destination
17,101,101,2019-01-20 11:19:35,2019-01-20 09:25:12,No.101_No.101,Destination
18,101,101,2019-01-20 12:02:41,2019-01-20 11:20:03,No.101_No.101,Destination
19,101,101,2019-01-20 17:35:54,2019-01-20 17:24:09,No.101_No.101,Destination
20,101,101,2019-01-21 05:05:10,2019-01-21 03:12:32,No.101_No.101,Destination
21,101,101,2019-01-23 17:38:47,2019-01-23 15:52:26,No.101_No.101,Destination
22,101,101,2019-01-25 13:13:48,2019-01-25 12:42:50,No.101_No.101,Destination
23,101,101,2019-01-26 16:26:28,2019-01-26 15:31:32,No.101_No.101,Destination
24,101,101,2019-01-26 19:52:07,2019-01-26 18:55:36,No.101_No.101,Destination
25,101,101,2019-01-26 20:03:13,2019-01-26 19:50:00,No.101_No.101,Destination
26,101,101,2019-01-26 23:48:54,2019-01-26 23:26:27,No.101_No.101,Destination
27,101,101,2019-01-27 18:03:35,2019-01-27 17:16:00,No.101_No.101,Destination
28,101,101,2019-01-27 19:13:38,2019-01-27 18:59:45,No.101_No.101,Destination
29,101,101,2019-01-27 23:54:43,2019-01-27 23:50:28,No.101_No.101,Destination
...,...,...,...,...,...,...
5325963,3542,3542,2019-05-24 02:13:23,2019-05-24 01:19:52,No.3542_No.3542,Destination
5325964,3542,3542,2019-05-24 15:22:38,2019-05-24 15:00:12,No.3542_No.3542,Destination
5325965,3542,3542,2019-05-24 17:42:54,2019-05-24 17:08:42,No.3542_No.3542,Destination
5325966,3542,3542,2019-05-24 22:16:58,2019-05-24 21:31:11,No.3542_No.3542,Destination
5325967,3542,3542,2019-05-25 10:04:18,2019-05-25 09:23:50,No.3542_No.3542,Destination
5325968,3542,3542,2019-05-25 13:24:15,2019-05-25 12:28:26,No.3542_No.3542,Destination
5325969,3542,3542,2019-05-25 17:54:10,2019-05-25 16:56:54,No.3542_No.3542,Destination
5325970,3542,3542,2019-05-25 19:38:25,2019-05-25 18:54:03,No.3542_No.3542,Destination
5325971,3542,3542,2019-05-25 20:44:25,2019-05-25 19:03:56,No.3542_No.3542,Destination
5325972,3542,3542,2019-05-25 23:07:44,2019-05-25 22:22:09,No.3542_No.3542,Destination
5325973,3542,3542,2019-05-25 23:07:56,2019-05-25 22:20:25,No.3542_No.3542,Destination
5325974,3542,3542,2019-05-25 23:08:01,2019-05-25 22:18:29,No.3542_No.3542,Destination
5325975,3542,3542,2019-05-26 13:24:08,2019-05-26 13:04:34,No.3542_No.3542,Destination
5325976,3542,3542,2019-05-26 17:46:00,2019-05-26 17:11:43,No.3542_No.3542,Destination
5325977,3542,3542,2019-05-26 21:51:09,2019-05-26 20:59:56,No.3542_No.3542,Destination
5325978,3542,3542,2019-05-27 00:13:50,2019-05-26 22:21:42,No.3542_No.3542,Destination
5325979,3542,3542,2019-05-27 05:40:35,2019-05-26 22:21:20,No.3542_No.3542,Destination
5325980,3542,3542,2019-05-27 05:54:36,2019-05-27 05:41:25,No.3542_No.3542,Destination
5325981,3542,3542,2019-05-27 17:10:44,2019-05-27 17:00:52,No.3542_No.3542,Destination
5325982,3542,3542,2019-05-28 05:52:05,2019-05-28 05:45:19,No.3542_No.3542,Destination
5325983,3542,3542,2019-05-28 10:10:27,2019-05-28 08:25:19,No.3542_No.3542,Destination
5325984,3542,3542,2019-05-28 15:54:14,2019-05-28 15:24:35,No.3542_No.3542,Destination
5325985,3542,3542,2019-05-28 18:18:28,2019-05-28 17:29:00,No.3542_No.3542,Destination
5325986,3542,3542,2019-05-28 20:29:06,2019-05-28 20:25:55,No.3542_No.3542,Destination
5325987,3542,3542,2019-05-29 17:51:36,2019-05-29 17:35:35,No.3542_No.3542,Destination
5325988,3542,3542,2019-05-29 23:09:24,2019-05-29 22:07:08,No.3542_No.3542,Destination
5325989,3542,3542,2019-05-30 06:03:06,2019-05-30 05:55:57,No.3542_No.3542,Destination
5325990,3542,3542,2019-05-30 10:07:55,2019-05-30 08:19:39,No.3542_No.3542,Destination
5325991,3542,3542,2019-05-30 15:31:08,2019-05-30 15:07:22,No.3542_No.3542,Destination
5325992,3542,3542,2019-05-31 08:47:34,2019-05-31 08:35:27,No.3542_No.3542,Destination

In [14]:
origin = origin.drop(columns=['반납대여소번호', '반납일시']).copy()
origin = origin.rename(columns={"대여대여소번호": "대여소번호", "대여일시": "일시"}).copy()
origin = origin.drop(columns=['일시']).copy()
origin

         대여소번호          Path ID Origin-Destination
0          101    No.101_No.101             Origin
1          101    No.101_No.101             Origin
2          101    No.101_No.101             Origin
3          101    No.101_No.101             Origin
4          101    No.101_No.101             Origin
5          101    No.101_No.101             Origin
6          101    No.101_No.101             Origin
7          101    No.101_No.101             Origin
8          101    No.101_No.101             Origin
9          101    No.101_No.101             Origin
10         101    No.101_No.101             Origin
11         101    No.101_No.101             Origin
12         101    No.101_No.101             Origin
13         101    No.101_No.101             Origin
14         101    No.101_No.101             Origin
15         101    No.101_No.101             Origin
16         101    No.101_No.101             Origin
17         101    No.101_No.101             Origin
18         101    No.101_No.101             Origin
19         101    No.101_No.101             Origin
20         101    No.101_No.101             Origin
21         101    No.101_No.101             Origin
22         101    No.101_No.101             Origin
23         101    No.101_No.101             Origin
24         101    No.101_No.101             Origin
25         101    No.101_No.101             Origin
26         101    No.101_No.101             Origin
27         101    No.101_No.101             Origin
28         101    No.101_No.101             Origin
29         101    No.101_No.101             Origin
...        ...              ...                ...
5325963   3542  No.3542_No.3542             Origin
5325964   3542  No.3542_No.3542             Origin
5325965   3542  No.3542_No.3542             Origin
5325966   3542  No.3542_No.3542             Origin
5325967   3542  No.3542_No.3542             Origin
5325968   3542  No.3542_No.3542             Origin
5325969   3542  No.3542_No.3542             Origin
5325970   3542  No.3542_No.3542             Origin
5325971   3542  No.3542_No.3542             Origin
5325972   3542  No.3542_No.3542             Origin
5325973   3542  No.3542_No.3542             Origin
5325974   3542  No.3542_No.3542             Origin
5325975   3542  No.3542_No.3542             Origin
5325976   3542  No.3542_No.3542             Origin
5325977   3542  No.3542_No.3542             Origin
5325978   3542  No.3542_No.3542             Origin
5325979   3542  No.3542_No.3542             Origin
5325980   3542  No.3542_No.3542             Origin
5325981   3542  No.3542_No.3542             Origin
5325982   3542  No.3542_No.3542             Origin
5325983   3542  No.3542_No.3542             Origin
5325984   3542  No.3542_No.3542             Origin
5325985   3542  No.3542_No.3542             Origin
5325986   3542  No.3542_No.3542             Origin
5325987   3542  No.3542_No.3542             Origin
5325988   3542  No.3542_No.3542             Origin
5325989   3542  No.3542_No.3542             Origin
5325990   3542  No.3542_No.3542             Origin
5325991   3542  No.3542_No.3542             Origin
5325992   3542  No.3542_No.3542             Origin

[5325993 rows x 3 columns]

In [15]:
origin['Path ID'].value_counts()

No.207_No.207      10088
No.502_No.502       9541
No.3515_No.3515     5396
No.2219_No.2219     4076
No.2183_No.2102     3830
No.2102_No.2183     3544
No.152_No.152       3533
No.113_No.183       3266
No.2102_No.2102     3121
No.186_No.186       2585
No.272_No.272       2420
No.907_No.907       2411
No.502_No.548       2347
No.2002_No.2002     2324
No.592_No.590       2286
No.183_No.113       2222
No.2183_No.2183     2176
No.2025_No.2025     2133
No.565_No.565       2132
No.3533_No.502      2086
No.590_No.592       1993
No.1827_No.1827     1956
No.2301_No.2301     1912
No.583_No.583       1908
No.502_No.593       1861
No.1160_No.1160     1846
No.2050_No.2013     1827
No.2202_No.2206     1790
No.2102_No.2107     1777
No.2262_No.2262     1776
                   ...
No.2279_No.1305        1
No.393_No.161          1
No.2135_No.2272        1
No.288_No.241          1
No.908_No.835          1
No.2214_No.1961        1
No.1283_No.546         1
No.1407_No.361         1
No.310_No.1362         1
No.1455_No.1709        1
No.3500_No.1543        1
No.104_No.802          1
No.971_No.233          1
No.3535_No.2377        1
No.151_No.2280         1
No.2301_No.700         1
No.2353_No.839         1
No.661_No.1316         1
No.1346_No.1525        1
No.430_No.435          1
No.1049_No.1209        1
No.2603_No.2233        1
No.413_No.583          1
No.1305_No.590         1
No.2313_No.506         1
No.1447_No.2219        1
No.805_No.2210         1
No.363_No.368          1
No.2603_No.1224        1
No.374_No.2308         1
Name: Path ID, Length: 316263, dtype: int64

In [16]:
tmp = pd.DataFrame()
tmp['Path ID'] = origin['Path ID'].value_counts().index
tmp['Count'] = origin['Path ID'].value_counts().values
tmp

                Path ID  Count
0         No.207_No.207  10088
1         No.502_No.502   9541
2       No.3515_No.3515   5396
3       No.2219_No.2219   4076
4       No.2183_No.2102   3830
5       No.2102_No.2183   3544
6         No.152_No.152   3533
7         No.113_No.183   3266
8       No.2102_No.2102   3121
9         No.186_No.186   2585
10        No.272_No.272   2420
11        No.907_No.907   2411
12        No.502_No.548   2347
13      No.2002_No.2002   2324
14        No.592_No.590   2286
15        No.183_No.113   2222
16      No.2183_No.2183   2176
17      No.2025_No.2025   2133
18        No.565_No.565   2132
19       No.3533_No.502   2086
20        No.590_No.592   1993
21      No.1827_No.1827   1956
22      No.2301_No.2301   1912
23        No.583_No.583   1908
24        No.502_No.593   1861
25      No.1160_No.1160   1846
26      No.2050_No.2013   1827
27      No.2202_No.2206   1790
28      No.2102_No.2107   1777
29      No.2262_No.2262   1776
...                 ...    ...
316233  No.2279_No.1305      1
316234    No.393_No.161      1
316235  No.2135_No.2272      1
316236    No.288_No.241      1
316237    No.908_No.835      1
316238  No.2214_No.1961      1
316239   No.1283_No.546      1
316240   No.1407_No.361      1
316241   No.310_No.1362      1
316242  No.1455_No.1709      1
316243  No.3500_No.1543      1
316244    No.104_No.802      1
316245    No.971_No.233      1
316246  No.3535_No.2377      1
316247   No.151_No.2280      1
316248   No.2301_No.700      1
316249   No.2353_No.839      1
316250   No.661_No.1316      1
316251  No.1346_No.1525      1
316252    No.430_No.435      1
316253  No.1049_No.1209      1
316254  No.2603_No.2233      1
316255    No.413_No.583      1
316256   No.1305_No.590      1
316257   No.2313_No.506      1
316258  No.1447_No.2219      1
316259   No.805_No.2210      1
316260    No.363_No.368      1
316261  No.2603_No.1224      1
316262   No.374_No.2308      1

[316263 rows x 2 columns]

In [17]:
origin = origin.drop_duplicates(subset='Path ID', keep='first').reset_index(drop=True)
origin

        대여소번호          Path ID Origin-Destination
0         101    No.101_No.101             Origin
1         102    No.101_No.102             Origin
2         103    No.101_No.103             Origin
3         104    No.101_No.104             Origin
4         105    No.101_No.105             Origin
5         106    No.101_No.106             Origin
6         107    No.101_No.107             Origin
7         108    No.101_No.108             Origin
8         109    No.101_No.109             Origin
9         110    No.101_No.110             Origin
10        111    No.101_No.111             Origin
11        112    No.101_No.112             Origin
12        113    No.101_No.113             Origin
13        114    No.101_No.114             Origin
14        115    No.101_No.115             Origin
15        116    No.101_No.116             Origin
16        118    No.101_No.118             Origin
17        119    No.101_No.119             Origin
18        120    No.101_No.120             Origin
19        121    No.101_No.121             Origin
20        122    No.101_No.122             Origin
21        123    No.101_No.123             Origin
22        124    No.101_No.124             Origin
23        125    No.101_No.125             Origin
24        127    No.101_No.127             Origin
25        128    No.101_No.128             Origin
26        129    No.101_No.129             Origin
27        130    No.101_No.130             Origin
28        131    No.101_No.131             Origin
29        133    No.101_No.133             Origin
...       ...              ...                ...
316233   2622  No.3542_No.2622             Origin
316234   3500  No.3542_No.3500             Origin
316235   3501  No.3542_No.3501             Origin
316236   3502  No.3542_No.3502             Origin
316237   3503  No.3542_No.3503             Origin
316238   3504  No.3542_No.3504             Origin
316239   3505  No.3542_No.3505             Origin
316240   3506  No.3542_No.3506             Origin
316241   3507  No.3542_No.3507             Origin
316242   3508  No.3542_No.3508             Origin
316243   3509  No.3542_No.3509             Origin
316244   3510  No.3542_No.3510             Origin
316245   3511  No.3542_No.3511             Origin
316246   3516  No.3542_No.3516             Origin
316247   3517  No.3542_No.3517             Origin
316248   3518  No.3542_No.3518             Origin
316249   3520  No.3542_No.3520             Origin
316250   3521  No.3542_No.3521             Origin
316251   3523  No.3542_No.3523             Origin
316252   3524  No.3542_No.3524             Origin
316253   3528  No.3542_No.3528             Origin
316254   3529  No.3542_No.3529             Origin
316255   3533  No.3542_No.3533             Origin
316256   3534  No.3542_No.3534             Origin
316257   3535  No.3542_No.3535             Origin
316258   3536  No.3542_No.3536             Origin
316259   3537  No.3542_No.3537             Origin
316260   3538  No.3542_No.3538             Origin
316261   3541  No.3542_No.3541             Origin
316262   3542  No.3542_No.3542             Origin

[316263 rows x 3 columns]

In [18]:
origin = pd.merge(origin,tmp,on='Path ID')

In [19]:
destination = destination.drop(columns=['대여대여소번호', '대여일시']).copy()
destination = destination.rename(columns={"반납대여소번호": "대여소번호", "반납일시": "일시"}).copy()
destination = destination.drop(columns=['일시']).copy()
destination

         대여소번호          Path ID Origin-Destination
0          101    No.101_No.101        Destination
1          101    No.101_No.101        Destination
2          101    No.101_No.101        Destination
3          101    No.101_No.101        Destination
4          101    No.101_No.101        Destination
5          101    No.101_No.101        Destination
6          101    No.101_No.101        Destination
7          101    No.101_No.101        Destination
8          101    No.101_No.101        Destination
9          101    No.101_No.101        Destination
10         101    No.101_No.101        Destination
11         101    No.101_No.101        Destination
12         101    No.101_No.101        Destination
13         101    No.101_No.101        Destination
14         101    No.101_No.101        Destination
15         101    No.101_No.101        Destination
16         101    No.101_No.101        Destination
17         101    No.101_No.101        Destination
18         101    No.101_No.101        Destination
19         101    No.101_No.101        Destination
20         101    No.101_No.101        Destination
21         101    No.101_No.101        Destination
22         101    No.101_No.101        Destination
23         101    No.101_No.101        Destination
24         101    No.101_No.101        Destination
25         101    No.101_No.101        Destination
26         101    No.101_No.101        Destination
27         101    No.101_No.101        Destination
28         101    No.101_No.101        Destination
29         101    No.101_No.101        Destination
...        ...              ...                ...
5325963   3542  No.3542_No.3542        Destination
5325964   3542  No.3542_No.3542        Destination
5325965   3542  No.3542_No.3542        Destination
5325966   3542  No.3542_No.3542        Destination
5325967   3542  No.3542_No.3542        Destination
5325968   3542  No.3542_No.3542        Destination
5325969   3542  No.3542_No.3542        Destination
5325970   3542  No.3542_No.3542        Destination
5325971   3542  No.3542_No.3542        Destination
5325972   3542  No.3542_No.3542        Destination
5325973   3542  No.3542_No.3542        Destination
5325974   3542  No.3542_No.3542        Destination
5325975   3542  No.3542_No.3542        Destination
5325976   3542  No.3542_No.3542        Destination
5325977   3542  No.3542_No.3542        Destination
5325978   3542  No.3542_No.3542        Destination
5325979   3542  No.3542_No.3542        Destination
5325980   3542  No.3542_No.3542        Destination
5325981   3542  No.3542_No.3542        Destination
5325982   3542  No.3542_No.3542        Destination
5325983   3542  No.3542_No.3542        Destination
5325984   3542  No.3542_No.3542        Destination
5325985   3542  No.3542_No.3542        Destination
5325986   3542  No.3542_No.3542        Destination
5325987   3542  No.3542_No.3542        Destination
5325988   3542  No.3542_No.3542        Destination
5325989   3542  No.3542_No.3542        Destination
5325990   3542  No.3542_No.3542        Destination
5325991   3542  No.3542_No.3542        Destination
5325992   3542  No.3542_No.3542        Destination

[5325993 rows x 3 columns]

In [20]:
tmpp = pd.DataFrame()
tmpp['Path ID'] = destination['Path ID'].value_counts().index
tmpp['Count'] = destination['Path ID'].value_counts().values
tmpp

                Path ID  Count
0         No.207_No.207  10088
1         No.502_No.502   9541
2       No.3515_No.3515   5396
3       No.2219_No.2219   4076
4       No.2183_No.2102   3830
5       No.2102_No.2183   3544
6         No.152_No.152   3533
7         No.113_No.183   3266
8       No.2102_No.2102   3121
9         No.186_No.186   2585
10        No.272_No.272   2420
11        No.907_No.907   2411
12        No.502_No.548   2347
13      No.2002_No.2002   2324
14        No.592_No.590   2286
15        No.183_No.113   2222
16      No.2183_No.2183   2176
17      No.2025_No.2025   2133
18        No.565_No.565   2132
19       No.3533_No.502   2086
20        No.590_No.592   1993
21      No.1827_No.1827   1956
22      No.2301_No.2301   1912
23        No.583_No.583   1908
24        No.502_No.593   1861
25      No.1160_No.1160   1846
26      No.2050_No.2013   1827
27      No.2202_No.2206   1790
28      No.2102_No.2107   1777
29      No.2262_No.2262   1776
...                 ...    ...
316233  No.2279_No.1305      1
316234    No.393_No.161      1
316235  No.2135_No.2272      1
316236    No.288_No.241      1
316237    No.908_No.835      1
316238  No.2214_No.1961      1
316239   No.1283_No.546      1
316240   No.1407_No.361      1
316241   No.310_No.1362      1
316242  No.1455_No.1709      1
316243  No.3500_No.1543      1
316244    No.104_No.802      1
316245    No.971_No.233      1
316246  No.3535_No.2377      1
316247   No.151_No.2280      1
316248   No.2301_No.700      1
316249   No.2353_No.839      1
316250   No.661_No.1316      1
316251  No.1346_No.1525      1
316252    No.430_No.435      1
316253  No.1049_No.1209      1
316254  No.2603_No.2233      1
316255    No.413_No.583      1
316256   No.1305_No.590      1
316257   No.2313_No.506      1
316258  No.1447_No.2219      1
316259   No.805_No.2210      1
316260    No.363_No.368      1
316261  No.2603_No.1224      1
316262   No.374_No.2308      1

[316263 rows x 2 columns]

In [21]:
destination = pd.merge(destination,tmp,on='Path ID')

In [22]:
destination = destination.drop_duplicates(subset='Path ID', keep='first').reset_index(drop=True)
destination

        대여소번호          Path ID Origin-Destination  Count
0         101    No.101_No.101        Destination    314
1         101    No.101_No.102        Destination    241
2         101    No.101_No.103        Destination    115
3         101    No.101_No.104        Destination    226
4         101    No.101_No.105        Destination     58
5         101    No.101_No.106        Destination    270
6         101    No.101_No.107        Destination     73
7         101    No.101_No.108        Destination     48
8         101    No.101_No.109        Destination     39
9         101    No.101_No.110        Destination      4
10        101    No.101_No.111        Destination     57
11        101    No.101_No.112        Destination     71
12        101    No.101_No.113        Destination     71
13        101    No.101_No.114        Destination     56
14        101    No.101_No.115        Destination      9
15        101    No.101_No.116        Destination      8
16        101    No.101_No.118        Destination      5
17        101    No.101_No.119        Destination      8
18        101    No.101_No.120        Destination      2
19        101    No.101_No.121        Destination      3
20        101    No.101_No.122        Destination      7
21        101    No.101_No.123        Destination      1
22        101    No.101_No.124        Destination      6
23        101    No.101_No.125        Destination      2
24        101    No.101_No.127        Destination      5
25        101    No.101_No.128        Destination      9
26        101    No.101_No.129        Destination     13
27        101    No.101_No.130        Destination      9
28        101    No.101_No.131        Destination      3
29        101    No.101_No.133        Destination      1
...       ...              ...                ...    ...
316233   3542  No.3542_No.2622        Destination      2
316234   3542  No.3542_No.3500        Destination     15
316235   3542  No.3542_No.3501        Destination     83
316236   3542  No.3542_No.3502        Destination      4
316237   3542  No.3542_No.3503        Destination     14
316238   3542  No.3542_No.3504        Destination     60
316239   3542  No.3542_No.3505        Destination     10
316240   3542  No.3542_No.3506        Destination      4
316241   3542  No.3542_No.3507        Destination    149
316242   3542  No.3542_No.3508        Destination     71
316243   3542  No.3542_No.3509        Destination     47
316244   3542  No.3542_No.3510        Destination     22
316245   3542  No.3542_No.3511        Destination      1
316246   3542  No.3542_No.3516        Destination     55
316247   3542  No.3542_No.3517        Destination      4
316248   3542  No.3542_No.3518        Destination     35
316249   3542  No.3542_No.3520        Destination     47
316250   3542  No.3542_No.3521        Destination     21
316251   3542  No.3542_No.3523        Destination     21
316252   3542  No.3542_No.3524        Destination      3
316253   3542  No.3542_No.3528        Destination     37
316254   3542  No.3542_No.3529        Destination     51
316255   3542  No.3542_No.3533        Destination    109
316256   3542  No.3542_No.3534        Destination     57
316257   3542  No.3542_No.3535        Destination     35
316258   3542  No.3542_No.3536        Destination      7
316259   3542  No.3542_No.3537        Destination     39
316260   3542  No.3542_No.3538        Destination     10
316261   3542  No.3542_No.3541        Destination     17
316262   3542  No.3542_No.3542        Destination    216

[316263 rows x 4 columns]

In [23]:
origin['idx'] = origin.index
destination['idx'] = destination.index

In [24]:
origin

        대여소번호          Path ID Origin-Destination  Count     idx
0         101    No.101_No.101             Origin    314       0
1         102    No.101_No.102             Origin    241       1
2         103    No.101_No.103             Origin    115       2
3         104    No.101_No.104             Origin    226       3
4         105    No.101_No.105             Origin     58       4
5         106    No.101_No.106             Origin    270       5
6         107    No.101_No.107             Origin     73       6
7         108    No.101_No.108             Origin     48       7
8         109    No.101_No.109             Origin     39       8
9         110    No.101_No.110             Origin      4       9
10        111    No.101_No.111             Origin     57      10
11        112    No.101_No.112             Origin     71      11
12        113    No.101_No.113             Origin     71      12
13        114    No.101_No.114             Origin     56      13
14        115    No.101_No.115             Origin      9      14
15        116    No.101_No.116             Origin      8      15
16        118    No.101_No.118             Origin      5      16
17        119    No.101_No.119             Origin      8      17
18        120    No.101_No.120             Origin      2      18
19        121    No.101_No.121             Origin      3      19
20        122    No.101_No.122             Origin      7      20
21        123    No.101_No.123             Origin      1      21
22        124    No.101_No.124             Origin      6      22
23        125    No.101_No.125             Origin      2      23
24        127    No.101_No.127             Origin      5      24
25        128    No.101_No.128             Origin      9      25
26        129    No.101_No.129             Origin     13      26
27        130    No.101_No.130             Origin      9      27
28        131    No.101_No.131             Origin      3      28
29        133    No.101_No.133             Origin      1      29
...       ...              ...                ...    ...     ...
316233   2622  No.3542_No.2622             Origin      2  316233
316234   3500  No.3542_No.3500             Origin     15  316234
316235   3501  No.3542_No.3501             Origin     83  316235
316236   3502  No.3542_No.3502             Origin      4  316236
316237   3503  No.3542_No.3503             Origin     14  316237
316238   3504  No.3542_No.3504             Origin     60  316238
316239   3505  No.3542_No.3505             Origin     10  316239
316240   3506  No.3542_No.3506             Origin      4  316240
316241   3507  No.3542_No.3507             Origin    149  316241
316242   3508  No.3542_No.3508             Origin     71  316242
316243   3509  No.3542_No.3509             Origin     47  316243
316244   3510  No.3542_No.3510             Origin     22  316244
316245   3511  No.3542_No.3511             Origin      1  316245
316246   3516  No.3542_No.3516             Origin     55  316246
316247   3517  No.3542_No.3517             Origin      4  316247
316248   3518  No.3542_No.3518             Origin     35  316248
316249   3520  No.3542_No.3520             Origin     47  316249
316250   3521  No.3542_No.3521             Origin     21  316250
316251   3523  No.3542_No.3523             Origin     21  316251
316252   3524  No.3542_No.3524             Origin      3  316252
316253   3528  No.3542_No.3528             Origin     37  316253
316254   3529  No.3542_No.3529             Origin     51  316254
316255   3533  No.3542_No.3533             Origin    109  316255
316256   3534  No.3542_No.3534             Origin     57  316256
316257   3535  No.3542_No.3535             Origin     35  316257
316258   3536  No.3542_No.3536             Origin      7  316258
316259   3537  No.3542_No.3537             Origin     39  316259
316260   3538  No.3542_No.3538             Origin     10  316260
316261   3541  No.3542_No.3541             Origin     17  316261
316262   3542  No.3542_No.3542             Origin    216  316262

[316263 rows x 5 columns]

In [25]:
destination

        대여소번호          Path ID Origin-Destination  Count     idx
0         101    No.101_No.101        Destination    314       0
1         101    No.101_No.102        Destination    241       1
2         101    No.101_No.103        Destination    115       2
3         101    No.101_No.104        Destination    226       3
4         101    No.101_No.105        Destination     58       4
5         101    No.101_No.106        Destination    270       5
6         101    No.101_No.107        Destination     73       6
7         101    No.101_No.108        Destination     48       7
8         101    No.101_No.109        Destination     39       8
9         101    No.101_No.110        Destination      4       9
10        101    No.101_No.111        Destination     57      10
11        101    No.101_No.112        Destination     71      11
12        101    No.101_No.113        Destination     71      12
13        101    No.101_No.114        Destination     56      13
14        101    No.101_No.115        Destination      9      14
15        101    No.101_No.116        Destination      8      15
16        101    No.101_No.118        Destination      5      16
17        101    No.101_No.119        Destination      8      17
18        101    No.101_No.120        Destination      2      18
19        101    No.101_No.121        Destination      3      19
20        101    No.101_No.122        Destination      7      20
21        101    No.101_No.123        Destination      1      21
22        101    No.101_No.124        Destination      6      22
23        101    No.101_No.125        Destination      2      23
24        101    No.101_No.127        Destination      5      24
25        101    No.101_No.128        Destination      9      25
26        101    No.101_No.129        Destination     13      26
27        101    No.101_No.130        Destination      9      27
28        101    No.101_No.131        Destination      3      28
29        101    No.101_No.133        Destination      1      29
...       ...              ...                ...    ...     ...
316233   3542  No.3542_No.2622        Destination      2  316233
316234   3542  No.3542_No.3500        Destination     15  316234
316235   3542  No.3542_No.3501        Destination     83  316235
316236   3542  No.3542_No.3502        Destination      4  316236
316237   3542  No.3542_No.3503        Destination     14  316237
316238   3542  No.3542_No.3504        Destination     60  316238
316239   3542  No.3542_No.3505        Destination     10  316239
316240   3542  No.3542_No.3506        Destination      4  316240
316241   3542  No.3542_No.3507        Destination    149  316241
316242   3542  No.3542_No.3508        Destination     71  316242
316243   3542  No.3542_No.3509        Destination     47  316243
316244   3542  No.3542_No.3510        Destination     22  316244
316245   3542  No.3542_No.3511        Destination      1  316245
316246   3542  No.3542_No.3516        Destination     55  316246
316247   3542  No.3542_No.3517        Destination      4  316247
316248   3542  No.3542_No.3518        Destination     35  316248
316249   3542  No.3542_No.3520        Destination     47  316249
316250   3542  No.3542_No.3521        Destination     21  316250
316251   3542  No.3542_No.3523        Destination     21  316251
316252   3542  No.3542_No.3524        Destination      3  316252
316253   3542  No.3542_No.3528        Destination     37  316253
316254   3542  No.3542_No.3529        Destination     51  316254
316255   3542  No.3542_No.3533        Destination    109  316255
316256   3542  No.3542_No.3534        Destination     57  316256
316257   3542  No.3542_No.3535        Destination     35  316257
316258   3542  No.3542_No.3536        Destination      7  316258
316259   3542  No.3542_No.3537        Destination     39  316259
316260   3542  No.3542_No.3538        Destination     10  316260
316261   3542  No.3542_No.3541        Destination     17  316261
316262   3542  No.3542_No.3542        Destination    216  316262

[316263 rows x 5 columns]

In [26]:
temp = pd.concat([origin, destination], axis=0)

In [27]:
temp = temp.sort_values(by=['idx'], axis=0)

In [28]:
temp.reset_index(drop=True)

        대여소번호          Path ID Origin-Destination  Count     idx
0         101    No.101_No.101             Origin    314       0
1         101    No.101_No.101        Destination    314       0
2         101    No.101_No.102        Destination    241       1
3         102    No.101_No.102             Origin    241       1
4         103    No.101_No.103             Origin    115       2
5         101    No.101_No.103        Destination    115       2
6         104    No.101_No.104             Origin    226       3
7         101    No.101_No.104        Destination    226       3
8         105    No.101_No.105             Origin     58       4
9         101    No.101_No.105        Destination     58       4
10        101    No.101_No.106        Destination    270       5
11        106    No.101_No.106             Origin    270       5
12        101    No.101_No.107        Destination     73       6
13        107    No.101_No.107             Origin     73       6
14        101    No.101_No.108        Destination     48       7
15        108    No.101_No.108             Origin     48       7
16        101    No.101_No.109        Destination     39       8
17        109    No.101_No.109             Origin     39       8
18        101    No.101_No.110        Destination      4       9
19        110    No.101_No.110             Origin      4       9
20        101    No.101_No.111        Destination     57      10
21        111    No.101_No.111             Origin     57      10
22        101    No.101_No.112        Destination     71      11
23        112    No.101_No.112             Origin     71      11
24        113    No.101_No.113             Origin     71      12
25        101    No.101_No.113        Destination     71      12
26        114    No.101_No.114             Origin     56      13
27        101    No.101_No.114        Destination     56      13
28        115    No.101_No.115             Origin      9      14
29        101    No.101_No.115        Destination      9      14
...       ...              ...                ...    ...     ...
632496   3542  No.3542_No.3518        Destination     35  316248
632497   3518  No.3542_No.3518             Origin     35  316248
632498   3520  No.3542_No.3520             Origin     47  316249
632499   3542  No.3542_No.3520        Destination     47  316249
632500   3542  No.3542_No.3521        Destination     21  316250
632501   3521  No.3542_No.3521             Origin     21  316250
632502   3542  No.3542_No.3523        Destination     21  316251
632503   3523  No.3542_No.3523             Origin     21  316251
632504   3542  No.3542_No.3524        Destination      3  316252
632505   3524  No.3542_No.3524             Origin      3  316252
632506   3542  No.3542_No.3528        Destination     37  316253
632507   3528  No.3542_No.3528             Origin     37  316253
632508   3542  No.3542_No.3529        Destination     51  316254
632509   3529  No.3542_No.3529             Origin     51  316254
632510   3542  No.3542_No.3533        Destination    109  316255
632511   3533  No.3542_No.3533             Origin    109  316255
632512   3542  No.3542_No.3534        Destination     57  316256
632513   3534  No.3542_No.3534             Origin     57  316256
632514   3535  No.3542_No.3535             Origin     35  316257
632515   3542  No.3542_No.3535        Destination     35  316257
632516   3542  No.3542_No.3536        Destination      7  316258
632517   3536  No.3542_No.3536             Origin      7  316258
632518   3542  No.3542_No.3537        Destination     39  316259
632519   3537  No.3542_No.3537             Origin     39  316259
632520   3542  No.3542_No.3538        Destination     10  316260
632521   3538  No.3542_No.3538             Origin     10  316260
632522   3542  No.3542_No.3541        Destination     17  316261
632523   3541  No.3542_No.3541             Origin     17  316261
632524   3542  No.3542_No.3542             Origin    216  316262
632525   3542  No.3542_No.3542        Destination    216  316262

[632526 rows x 5 columns]

In [29]:
temp  = temp.sort_values(['idx', 'Origin-Destination'], ascending=[True, False])

In [30]:
temp = temp.reset_index(drop=True)
temp

        대여소번호          Path ID Origin-Destination  Count     idx
0         101    No.101_No.101             Origin    314       0
1         101    No.101_No.101        Destination    314       0
2         102    No.101_No.102             Origin    241       1
3         101    No.101_No.102        Destination    241       1
4         103    No.101_No.103             Origin    115       2
5         101    No.101_No.103        Destination    115       2
6         104    No.101_No.104             Origin    226       3
7         101    No.101_No.104        Destination    226       3
8         105    No.101_No.105             Origin     58       4
9         101    No.101_No.105        Destination     58       4
10        106    No.101_No.106             Origin    270       5
11        101    No.101_No.106        Destination    270       5
12        107    No.101_No.107             Origin     73       6
13        101    No.101_No.107        Destination     73       6
14        108    No.101_No.108             Origin     48       7
15        101    No.101_No.108        Destination     48       7
16        109    No.101_No.109             Origin     39       8
17        101    No.101_No.109        Destination     39       8
18        110    No.101_No.110             Origin      4       9
19        101    No.101_No.110        Destination      4       9
20        111    No.101_No.111             Origin     57      10
21        101    No.101_No.111        Destination     57      10
22        112    No.101_No.112             Origin     71      11
23        101    No.101_No.112        Destination     71      11
24        113    No.101_No.113             Origin     71      12
25        101    No.101_No.113        Destination     71      12
26        114    No.101_No.114             Origin     56      13
27        101    No.101_No.114        Destination     56      13
28        115    No.101_No.115             Origin      9      14
29        101    No.101_No.115        Destination      9      14
...       ...              ...                ...    ...     ...
632496   3518  No.3542_No.3518             Origin     35  316248
632497   3542  No.3542_No.3518        Destination     35  316248
632498   3520  No.3542_No.3520             Origin     47  316249
632499   3542  No.3542_No.3520        Destination     47  316249
632500   3521  No.3542_No.3521             Origin     21  316250
632501   3542  No.3542_No.3521        Destination     21  316250
632502   3523  No.3542_No.3523             Origin     21  316251
632503   3542  No.3542_No.3523        Destination     21  316251
632504   3524  No.3542_No.3524             Origin      3  316252
632505   3542  No.3542_No.3524        Destination      3  316252
632506   3528  No.3542_No.3528             Origin     37  316253
632507   3542  No.3542_No.3528        Destination     37  316253
632508   3529  No.3542_No.3529             Origin     51  316254
632509   3542  No.3542_No.3529        Destination     51  316254
632510   3533  No.3542_No.3533             Origin    109  316255
632511   3542  No.3542_No.3533        Destination    109  316255
632512   3534  No.3542_No.3534             Origin     57  316256
632513   3542  No.3542_No.3534        Destination     57  316256
632514   3535  No.3542_No.3535             Origin     35  316257
632515   3542  No.3542_No.3535        Destination     35  316257
632516   3536  No.3542_No.3536             Origin      7  316258
632517   3542  No.3542_No.3536        Destination      7  316258
632518   3537  No.3542_No.3537             Origin     39  316259
632519   3542  No.3542_No.3537        Destination     39  316259
632520   3538  No.3542_No.3538             Origin     10  316260
632521   3542  No.3542_No.3538        Destination     10  316260
632522   3541  No.3542_No.3541             Origin     17  316261
632523   3542  No.3542_No.3541        Destination     17  316261
632524   3542  No.3542_No.3542             Origin    216  316262
632525   3542  No.3542_No.3542        Destination    216  316262

[632526 rows x 5 columns]

In [33]:
info = pd.read_csv(r"C:\Users\19641\OSS_Project\opensourceproject\bicycle\공공자전거 대여소 정보_201905.CSV",engine = 'python')
info = info.drop(columns=['구분','대여소명']).copy()

In [34]:
info

      대여소번호         위도          경도  거치대수
0       101  37.549561  126.905754     5
1       102  37.556000  126.910454    20
2       103  37.554951  126.910835    14
3       104  37.550629  126.914986    13
4       105  37.550007  126.914825     5
5       106  37.548645  126.912827    10
6       107  37.557510  126.918503     5
7       108  37.552746  126.918617    10
8       109  37.547691  126.919983    10
9       110  37.568199  126.917847    20
10      111  37.547871  126.923531    10
11      112  37.549202  126.923203    10
12      113  37.557499  126.923805    25
13      114  37.557060  126.924423    15
14      115  37.558933  126.927116    15
15      116  37.564541  126.927071     5
16      117  37.591160  126.941330    25
17      118  37.547733  126.931763    10
18      119  37.545284  126.931053    10
19      120  37.545242  126.934113     5
20      121  37.549767  126.933174    15
21      122  37.547249  126.939293    10
22      123  37.594330  126.947388    20
23      124  37.551140  126.936989    20
24      125  37.549484  126.938950    15
25      126  37.550411  126.943848    20
26      127  37.553520  126.936951    15
27      128  37.555496  126.936340    20
28      129  37.555054  126.937569    15
29      130  37.554859  126.936157    10
...     ...        ...         ...   ...
1507   3510  37.568649  127.086250    10
1508   3511  37.551250  127.035103    10
1509   3513  37.564610  127.029198    10
1510   3514  37.566261  127.023697    10
1511   3515  37.542816  127.042084    20
1512   3516  37.543705  127.093246    10
1513   3517  37.562527  127.082275    10
1514   3518  37.556862  127.079140     8
1515   3519  37.562607  127.051308    10
1516   3520  37.542519  127.084084    10
1517   3521  37.543427  127.096619    10
1518   3522  37.561245  127.048851     9
1519   3523  37.541718  127.080170    10
1520   3524  37.550236  127.073822    15
1521   3525  37.546089  127.025070    15
1522   3527  37.561790  127.024391     8
1523   3528  37.550598  127.110512     8
1524   3529  37.549789  127.075928    15
1525   3530  37.560146  127.026360    15
1526   3531  37.554779  127.024841    15
1527   3532  37.560680  127.026779    15
1528   3533  37.539139  127.070618    10
1529   3534  37.540138  127.069283    12
1530   3535  37.559158  127.087517    10
1531   3536  37.531811  127.080742    10
1532   3537  37.548489  127.093758    15
1533   3538  37.550892  127.044762    14
1534   3539  37.563820  127.132843    10
1535   3541  37.545040  127.089958    17
1536   3542  37.545040  127.089958    17

[1537 rows x 4 columns]

In [35]:
fin = pd.merge(temp, info, on='대여소번호')
fin = fin.sort_values(['idx', 'Origin-Destination'], ascending=[True, False])
fin = fin.drop(columns=['idx']).copy()
fin = fin.reset_index(drop=True)
fin

,대여소번호,Path ID,Origin-Destination,Count,위도,경도,거치대수
0,101,No.101_No.101,Origin,314,37.549561,126.905754,5
1,101,No.101_No.101,Destination,314,37.549561,126.905754,5
2,102,No.101_No.102,Origin,241,37.556000,126.910454,20
3,101,No.101_No.102,Destination,241,37.549561,126.905754,5
4,103,No.101_No.103,Origin,115,37.554951,126.910835,14
5,101,No.101_No.103,Destination,115,37.549561,126.905754,5
6,104,No.101_No.104,Origin,226,37.550629,126.914986,13
7,101,No.101_No.104,Destination,226,37.549561,126.905754,5
8,105,No.101_No.105,Origin,58,37.550007,126.914825,5
9,101,No.101_No.105,Destination,58,37.549561,126.905754,5
10,106,No.101_No.106,Origin,270,37.548645,126.912827,10
11,101,No.101_No.106,Destination,270,37.549561,126.905754,5
12,107,No.101_No.107,Origin,73,37.557510,126.918503,5
13,101,No.101_No.107,Destination,73,37.549561,126.905754,5
14,108,No.101_No.108,Origin,48,37.552746,126.918617,10
15,101,No.101_No.108,Destination,48,37.549561,126.905754,5
16,109,No.101_No.109,Origin,39,37.547691,126.919983,10
17,101,No.101_No.109,Destination,39,37.549561,126.905754,5
18,110,No.101_No.110,Origin,4,37.568199,126.917847,20
19,101,No.101_No.110,Destination,4,37.549561,126.905754,5
20,111,No.101_No.111,Origin,57,37.547871,126.923531,10
21,101,No.101_No.111,Destination,57,37.549561,126.905754,5
22,112,No.101_No.112,Origin,71,37.549202,126.923203,10
23,101,No.101_No.112,Destination,71,37.549561,126.905754,5
24,113,No.101_No.113,Origin,71,37.557499,126.923805,25
25,101,No.101_No.113,Destination,71,37.549561,126.905754,5
26,114,No.101_No.114,Origin,56,37.557060,126.924423,15
27,101,No.101_No.114,Destination,56,37.549561,126.905754,5
28,115,No.101_No.115,Origin,9,37.558933,126.927116,15
29,101,No.101_No.115,Destination,9,37.549561,126.905754,5
...,...,...,...,...,...,...,...
632496,3518,No.3542_No.3518,Origin,35,37.556862,127.079140,8
632497,3542,No.3542_No.3518,Destination,35,37.545040,127.089958,17
632498,3520,No.3542_No.3520,Origin,47,37.542519,127.084084,10
632499,3542,No.3542_No.3520,Destination,47,37.545040,127.089958,17
632500,3521,No.3542_No.3521,Origin,21,37.543427,127.096619,10
632501,3542,No.3542_No.3521,Destination,21,37.545040,127.089958,17
632502,3523,No.3542_No.3523,Origin,21,37.541718,127.080170,10
632503,3542,No.3542_No.3523,Destination,21,37.545040,127.089958,17
632504,3524,No.3542_No.3524,Origin,3,37.550236,127.073822,15
632505,3542,No.3542_No.3524,Destination,3,37.545040,127.089958,17
632506,3528,No.3542_No.3528,Origin,37,37.550598,127.110512,8
632507,3542,No.3542_No.3528,Destination,37,37.545040,127.089958,17
632508,3529,No.3542_No.3529,Origin,51,37.549789,127.075928,15
632509,3542,No.3542_No.3529,Destination,51,37.545040,127.089958,17
632510,3533,No.3542_No.3533,Origin,109,37.539139,127.070618,10
632511,3542,No.3542_No.3533,Destination,109,37.545040,127.089958,17
632512,3534,No.3542_No.3534,Origin,57,37.540138,127.069283,12
632513,3542,No.3542_No.3534,Destination,57,37.545040,127.089958,17
632514,3535,No.3542_No.3535,Origin,35,37.559158,127.087517,10
632515,3542,No.3542_No.3535,Destination,35,37.545040,127.089958,17
632516,3536,No.3542_No.3536,Origin,7,37.531811,127.080742,10
632517,3542,No.3542_No.3536,Destination,7,37.545040,127.089958,17
632518,3537,No.3542_No.3537,Origin,39,37.548489,127.093758,15
632519,3542,No.3542_No.3537,Destination,39,37.545040,127.089958,17
632520,3538,No.3542_No.3538,Origin,10,37.550892,127.044762,14
632521,3542,No.3542_No.3538,Destination,10,37.545040,127.089958,17
632522,3541,No.3542_No.3541,Origin,17,37.545040,127.089958,17
632523,3542,No.3542_No.3541,Destination,17,37.545040,127.089958,17
632524,3542,No.3542_No.3542,Origin,216,37.545040,127.089958,17
632525,3542,No.3542_No.3542,Destination,216,37.545040,127.089958,17

In [36]:
arr = 'No.' + fin['대여소번호'].map(str)
fin['대여소번호'] = arr

In [37]:
fin

,대여소번호,Path ID,Origin-Destination,Count,위도,경도,거치대수
0,No.101,No.101_No.101,Origin,314,37.549561,126.905754,5
1,No.101,No.101_No.101,Destination,314,37.549561,126.905754,5
2,No.102,No.101_No.102,Origin,241,37.556000,126.910454,20
3,No.101,No.101_No.102,Destination,241,37.549561,126.905754,5
4,No.103,No.101_No.103,Origin,115,37.554951,126.910835,14
5,No.101,No.101_No.103,Destination,115,37.549561,126.905754,5
6,No.104,No.101_No.104,Origin,226,37.550629,126.914986,13
7,No.101,No.101_No.104,Destination,226,37.549561,126.905754,5
8,No.105,No.101_No.105,Origin,58,37.550007,126.914825,5
9,No.101,No.101_No.105,Destination,58,37.549561,126.905754,5
10,No.106,No.101_No.106,Origin,270,37.548645,126.912827,10
11,No.101,No.101_No.106,Destination,270,37.549561,126.905754,5
12,No.107,No.101_No.107,Origin,73,37.557510,126.918503,5
13,No.101,No.101_No.107,Destination,73,37.549561,126.905754,5
14,No.108,No.101_No.108,Origin,48,37.552746,126.918617,10
15,No.101,No.101_No.108,Destination,48,37.549561,126.905754,5
16,No.109,No.101_No.109,Origin,39,37.547691,126.919983,10
17,No.101,No.101_No.109,Destination,39,37.549561,126.905754,5
18,No.110,No.101_No.110,Origin,4,37.568199,126.917847,20
19,No.101,No.101_No.110,Destination,4,37.549561,126.905754,5
20,No.111,No.101_No.111,Origin,57,37.547871,126.923531,10
21,No.101,No.101_No.111,Destination,57,37.549561,126.905754,5
22,No.112,No.101_No.112,Origin,71,37.549202,126.923203,10
23,No.101,No.101_No.112,Destination,71,37.549561,126.905754,5
24,No.113,No.101_No.113,Origin,71,37.557499,126.923805,25
25,No.101,No.101_No.113,Destination,71,37.549561,126.905754,5
26,No.114,No.101_No.114,Origin,56,37.557060,126.924423,15
27,No.101,No.101_No.114,Destination,56,37.549561,126.905754,5
28,No.115,No.101_No.115,Origin,9,37.558933,126.927116,15
29,No.101,No.101_No.115,Destination,9,37.549561,126.905754,5
...,...,...,...,...,...,...,...
632496,No.3518,No.3542_No.3518,Origin,35,37.556862,127.079140,8
632497,No.3542,No.3542_No.3518,Destination,35,37.545040,127.089958,17
632498,No.3520,No.3542_No.3520,Origin,47,37.542519,127.084084,10
632499,No.3542,No.3542_No.3520,Destination,47,37.545040,127.089958,17
632500,No.3521,No.3542_No.3521,Origin,21,37.543427,127.096619,10
632501,No.3542,No.3542_No.3521,Destination,21,37.545040,127.089958,17
632502,No.3523,No.3542_No.3523,Origin,21,37.541718,127.080170,10
632503,No.3542,No.3542_No.3523,Destination,21,37.545040,127.089958,17
632504,No.3524,No.3542_No.3524,Origin,3,37.550236,127.073822,15
632505,No.3542,No.3542_No.3524,Destination,3,37.545040,127.089958,17
632506,No.3528,No.3542_No.3528,Origin,37,37.550598,127.110512,8
632507,No.3542,No.3542_No.3528,Destination,37,37.545040,127.089958,17
632508,No.3529,No.3542_No.3529,Origin,51,37.549789,127.075928,15
632509,No.3542,No.3542_No.3529,Destination,51,37.545040,127.089958,17
632510,No.3533,No.3542_No.3533,Origin,109,37.539139,127.070618,10
632511,No.3542,No.3542_No.3533,Destination,109,37.545040,127.089958,17
632512,No.3534,No.3542_No.3534,Origin,57,37.540138,127.069283,12
632513,No.3542,No.3542_No.3534,Destination,57,37.545040,127.089958,17
632514,No.3535,No.3542_No.3535,Origin,35,37.559158,127.087517,10
632515,No.3542,No.3542_No.3535,Destination,35,37.545040,127.089958,17
632516,No.3536,No.3542_No.3536,Origin,7,37.531811,127.080742,10
632517,No.3542,No.3542_No.3536,Destination,7,37.545040,127.089958,17
632518,No.3537,No.3542_No.3537,Origin,39,37.548489,127.093758,15
632519,No.3542,No.3542_No.3537,Destination,39,37.545040,127.089958,17
632520,No.3538,No.3542_No.3538,Origin,10,37.550892,127.044762,14
632521,No.3542,No.3542_No.3538,Destination,10,37.545040,127.089958,17
632522,No.3541,No.3542_No.3541,Origin,17,37.545040,127.089958,17
632523,No.3542,No.3542_No.3541,Destination,17,37.545040,127.089958,17
632524,No.3542,No.3542_No.3542,Origin,216,37.545040,127.089958,17
632525,No.3542,No.3542_No.3542,Destination,216,37.545040,127.089958,17

In [38]:
test = fin['Path ID'].value_counts()
tst = pd.DataFrame()
tst['Path ID'] = test.index
tst['Count'] = test.values
tst

                Path ID  Count
0        No.374_No.2308      2
1         No.203_No.130      2
2         No.834_No.311      2
3       No.2251_No.2340      2
4       No.1060_No.1008      2
5        No.106_No.1985      2
6       No.1013_No.2608      2
7       No.2412_No.1244      2
8       No.3536_No.3521      2
9         No.642_No.521      2
10       No.2020_No.311      2
11      No.1056_No.1037      2
12        No.328_No.518      2
13       No.1354_No.316      2
14      No.1235_No.2322      2
15       No.2301_No.382      2
16       No.1148_No.275      2
17        No.841_No.415      2
18       No.1974_No.291      2
19       No.719_No.1140      2
20      No.1308_No.3104      2
21        No.147_No.302      2
22        No.516_No.546      2
23        No.290_No.723      2
24       No.2027_No.501      2
25        No.900_No.950      2
26       No.2337_No.825      2
27        No.641_No.642      2
28        No.162_No.116      2
29        No.719_No.701      2
...                 ...    ...
316233    No.949_No.962      2
316234    No.915_No.963      2
316235   No.2239_No.140      2
316236   No.534_No.2217      2
316237    No.334_No.390      2
316238   No.1804_No.291      2
316239  No.1195_No.1124      2
316240  No.1961_No.2115      2
316241  No.2107_No.1122      2
316242    No.428_No.826      2
316243    No.283_No.182      2
316244  No.2316_No.2376      2
316245  No.1946_No.1933      2
316246    No.831_No.825      2
316247    No.141_No.202      2
316248  No.1405_No.1640      2
316249  No.3536_No.3529      2
316250   No.206_No.2250      2
316251   No.946_No.1344      2
316252  No.1035_No.1015      2
316253    No.109_No.320      2
316254  No.2606_No.1211      2
316255  No.2231_No.2225      2
316256  No.2405_No.2273      2
316257    No.571_No.520      2
316258    No.379_No.838      2
316259  No.1212_No.2164      2
316260  No.2247_No.2339      2
316261  No.1634_No.1668      2
316262   No.754_No.1118      2

[316263 rows x 2 columns]

In [39]:
fin.to_csv('path.csv',encoding='utf-8-sig',index=False)

In [40]:
tst.to_csv('path_count.csv',encoding='utf-8-sig',index=False)

In [42]:
last = pd.read_csv(r"C:\Users\19641\OSS_Project\opensourceproject\bicycle\공공자전거 대여소 정보_201905.CSV",engine = 'python')
last

        구분  대여소번호                    대여소명         위도          경도  거치대수
0      마포구    101        101. (구)합정동 주민센터  37.549561  126.905754     5
1      마포구    102         102. 망원역 1번출구 앞  37.556000  126.910454    20
2      마포구    103         103. 망원역 2번출구 앞  37.554951  126.910835    14
3      마포구    104         104. 합정역 1번출구 앞  37.550629  126.914986    13
4      마포구    105         105. 합정역 5번출구 앞  37.550007  126.914825     5
5      마포구    106         106. 합정역 7번출구 앞  37.548645  126.912827    10
6      마포구    107    107. 신한은행 서교동금융센터점 앞  37.557510  126.918503     5
7      마포구    108            108. 서교동 사거리  37.552746  126.918617    10
8      마포구    109             109. 제일빌딩 앞  37.547691  126.919983    10
9     서대문구    110                110. 사천교  37.568199  126.917847    20
10     마포구    111         111. 상수역 2번출구 앞  37.547871  126.923531    10
11     마포구    112            112. 극동방송국 앞  37.549202  126.923203    10
12     마포구    113       113. 홍대입구역 2번출구 앞  37.557499  126.923805    25
13     마포구    114       114. 홍대입구역 8번출구 앞  37.557060  126.924423    15
14    서대문구    115          115. 사루비아 빌딩 앞  37.558933  126.927116    15
15    서대문구    116         116. 일진아이윌아파트 옆  37.564541  126.927071     5
16    서대문구    117              117. 홍은사거리  37.591160  126.941330    25
17     마포구    118        118. 광흥창역 2번출구 앞  37.547733  126.931763    10
18     마포구    119            119. 서강나루 공원  37.545284  126.931053    10
19     마포구    120            120. 신수동 사거리  37.545242  126.934113     5
20     마포구    121            121. 마포소방서 앞  37.549767  126.933174    15
21     마포구    122           122. 신성기사식당 앞  37.547249  126.939293    10
22    서대문구    123             123. 문화촌 공원  37.594330  126.947388    20
23     마포구    124         124. 서강대 정문 건너편  37.551140  126.936989    20
24     마포구    125           125. 서강대 남문 옆  37.549484  126.938950    15
25     마포구    126           126. 서강대 후문 옆  37.550411  126.943848    20
26     마포구    127            127. 현대벤처빌 앞  37.553520  126.936951    15
27    서대문구    128    128. 신촌역(2호선) 1번출구 옆  37.555496  126.936340    20
28     마포구    129    129. 신촌역(2호선) 6번출구 옆  37.555054  126.937569    15
29     마포구    130    130. 신촌역(2호선) 7번출구 앞  37.554859  126.936157    10
...    ...    ...                     ...        ...         ...   ...
1507   광진구   3510          3510. 중곡SK아파트앞  37.568649  127.086250    10
1508   성동구   3511          3511. 응봉역 1번출구  37.551250  127.035103    10
1509   성동구   3513        3513. 상왕십리역 1번출구  37.564610  127.029198    10
1510   성동구   3514            3514. 왕십리교회옆  37.566261  127.023697    10
1511   성동구   3515         3515. 서울숲 관리사무소  37.542816  127.042084    20
1512   광진구   3516        3516. 구의아리수정수센터앞  37.543705  127.093246    10
1513   광진구   3517             3517. 용마사거리  37.562527  127.082275    10
1514   광진구   3518         3518. 군자역 7번출구뒤  37.556862  127.079140     8
1515   성동구   3519         3519. 용답역 1번 출구  37.562607  127.051308    10
1516   광진구   3520             3520. 광진경찰서  37.542519  127.084084    10
1517   광진구   3521          3521. 현대홈타운 뒷길  37.543427  127.096619    10
1518   성동구   3522             3522. 사근삼거리  37.561245  127.048851     9
1519   광진구   3523  3523. 건국대학교 과학관(이과대) 앞  37.541718  127.080170    10
1520   광진구   3524             3524. 세종대학교  37.550236  127.073822    15
1521   성동구   3525                금호스포츠센터앞  37.546089  127.025070    15
1522   성동구   3527               왕십리 자이아파트  37.561790  127.024391     8
1523   광진구   3528                 광진정보도서관  37.550598  127.110512     8
1524   광진구   3529                어린이대공원정문  37.549789  127.075928    15
1525   성동구   3530        왕십리자이아파트 후문(삼거리)  37.560146  127.026360    15
1526   성동구   3531         논골사거리(금호도서관 입구)  37.554779  127.024841    15
1527   성동구   3532            왕십리KCC스위첸아파트  37.560680  127.026779    15
1528   광진구   3533        건대입구역 사거리(롯데백화점)  37.539139  127.070618    10
1529   광진구   3534            건대입구역 5번출구 뒤  37.540138  127.069283    12
1530   광진구   3535             중곡사거리(국민은행)  37.559158  127.087517    10
1531   광진구   3536               중앙농협(자양동)  37.531811  127.080742    10
1532   광진구   3537          아차산 휴먼시아 아파트 옆  37.548489  127.093758    15
1533   성동구   3538                서울숲 IT캐슬  37.550892  127.044762    14
1534   강동구   3539                    서원마을  37.563820  127.132843    10
1535   광진구   3541                  커먼그라운드  37.545040  127.089958    17
1536   광진구   3542            래미안 구의파크 스위트  37.545040  127.089958    17

[1537 rows x 6 columns]

In [43]:
last = last.drop(columns=['구분','위도','경도','거치대수']).copy()
last

      대여소번호                    대여소명
0       101        101. (구)합정동 주민센터
1       102         102. 망원역 1번출구 앞
2       103         103. 망원역 2번출구 앞
3       104         104. 합정역 1번출구 앞
4       105         105. 합정역 5번출구 앞
5       106         106. 합정역 7번출구 앞
6       107    107. 신한은행 서교동금융센터점 앞
7       108            108. 서교동 사거리
8       109             109. 제일빌딩 앞
9       110                110. 사천교
10      111         111. 상수역 2번출구 앞
11      112            112. 극동방송국 앞
12      113       113. 홍대입구역 2번출구 앞
13      114       114. 홍대입구역 8번출구 앞
14      115          115. 사루비아 빌딩 앞
15      116         116. 일진아이윌아파트 옆
16      117              117. 홍은사거리
17      118        118. 광흥창역 2번출구 앞
18      119            119. 서강나루 공원
19      120            120. 신수동 사거리
20      121            121. 마포소방서 앞
21      122           122. 신성기사식당 앞
22      123             123. 문화촌 공원
23      124         124. 서강대 정문 건너편
24      125           125. 서강대 남문 옆
25      126           126. 서강대 후문 옆
26      127            127. 현대벤처빌 앞
27      128    128. 신촌역(2호선) 1번출구 옆
28      129    129. 신촌역(2호선) 6번출구 옆
29      130    130. 신촌역(2호선) 7번출구 앞
...     ...                     ...
1507   3510          3510. 중곡SK아파트앞
1508   3511          3511. 응봉역 1번출구
1509   3513        3513. 상왕십리역 1번출구
1510   3514            3514. 왕십리교회옆
1511   3515         3515. 서울숲 관리사무소
1512   3516        3516. 구의아리수정수센터앞
1513   3517             3517. 용마사거리
1514   3518         3518. 군자역 7번출구뒤
1515   3519         3519. 용답역 1번 출구
1516   3520             3520. 광진경찰서
1517   3521          3521. 현대홈타운 뒷길
1518   3522             3522. 사근삼거리
1519   3523  3523. 건국대학교 과학관(이과대) 앞
1520   3524             3524. 세종대학교
1521   3525                금호스포츠센터앞
1522   3527               왕십리 자이아파트
1523   3528                 광진정보도서관
1524   3529                어린이대공원정문
1525   3530        왕십리자이아파트 후문(삼거리)
1526   3531         논골사거리(금호도서관 입구)
1527   3532            왕십리KCC스위첸아파트
1528   3533        건대입구역 사거리(롯데백화점)
1529   3534            건대입구역 5번출구 뒤
1530   3535             중곡사거리(국민은행)
1531   3536               중앙농협(자양동)
1532   3537          아차산 휴먼시아 아파트 옆
1533   3538                서울숲 IT캐슬
1534   3539                    서원마을
1535   3541                  커먼그라운드
1536   3542            래미안 구의파크 스위트

[1537 rows x 2 columns]

In [44]:
arr = 'No.' + last['대여소번호'].map(str)
last['대여소번호'] = arr

In [45]:
last.to_csv('name.csv',encoding='utf-8-sig',index=False)